import React, { useState } from 'react';
import Head from 'next/head';
import favicon from '../public/favicon.ico';
import Nav from '../components/Nav';
import Item from '../components/Item';

const Home = () => {
  const [items, setItems] = useState([
    { weight: 2.1, name: 'Item 1', url: "https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cGFudHN8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60" },
    { weight: 3, name: 'Item 2', url: "" },
    { weight: 7.2, name: 'Item 3', url: "" },
    { weight: 3, name: 'Item 4', url: "" },
    { weight: 5, name: 'Item 5', url: "" },
  ]);

  const [total, setTotal] = useState(0);
  const [weight, setWeight] = useState(0);

  const handlePost = () => {
    fetch('/bag', {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ total }),
    }).then((res) => res.json())
    .catch((error) => console.error('Error:', error))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon.src} />
      </Head>

      <main class="container">
        <Nav />
        <div class="d-flex flex-row">
          <div class="row">
            <div class="col-8">
              <img src="/bag.jpeg" alt="total" width="70%" />
              <button class="btn border" onClick={() => setTotal(0)}>Reset</button>
              <button class="btn border ms-3" nClick={handlePost}>Send</button>
            </div>
            <div class="col-4 border-start border-dark mt-2">
              {items.map((item) => (
                <div>
                  <Item weight={item.weight} url={item.url} setTotal={setTotal} total={total}/>
                </div>
              ))}
            </div>

          </div>
        </div>
        <div class="ms-5">
          <h2>Weight: {total} lbs</h2>
        </div>
        


        {/* <Tab.Group>
          <div class="container d-flex justify-content-center align-items-center border-bottom border-2 p-1">
            <Tab.List>
              <Tab class="btn fs-2">ACCOUNT SUMMARY</Tab>
              <Tab class="btn fs-2">PROMOTIONS</Tab>
              <Tab class="btn fs-2">WALLET</Tab>
            </Tab.List>
          </div>
          <Tab.Panels>
            <Tab.Panel>Content 1</Tab.Panel>
            <Tab.Panel>Content 2</Tab.Panel>
            <Tab.Panel>Content 3</Tab.Panel>
          </Tab.Panels>

        </Tab.Group> */}

      </main>
    </div>
  )
}

export default Home;
