import React, { useState } from 'react';
import Head from 'next/head';
import favicon from '../public/favicon.ico';
import Nav from '../components/Nav';
import Item from '../components/Item';

const Home = () => {
  const [items, setItems] = useState([
    { weight: 2.1, name: 'Item 1', url: "https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cGFudHN8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60" },
    { weight: 3, name: 'Item 2', url: "https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8aG9vZGllfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60" },
    { weight: 7.2, name: 'Item 3', url: "https://images.unsplash.com/photo-1604176354204-9268737828e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dHJvdXNlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60" },
    { weight: 3, name: 'Item 4', url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c2hvZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60" },
    { weight: 5, name: 'Item 5', url: "https://images.unsplash.com/photo-1598032895397-b9472444bf93?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8c2hpcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60" },
  ]);

  const [total, setTotal] = useState(0);

  const handlePost = () => {
    fetch('/bag', {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ total }),
    }).then((res) => res.json())
      .catch((error) => console.error('Error:', error))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon.src} />
      </Head>

      <main class="container">
        <Nav />
        <div class="d-flex flex-row">
          <div class="row">
            <div class="col-8">
              <img src="/bag.jpeg" alt="total" width="70%" />
              <button class="btn border" onClick={() => setTotal(0)}>Reset</button>
              <button class="btn border ms-3" nClick={handlePost}>Send</button>
            </div>
            <div class="col-4 border-start border-dark mt-2">
              {items.map((item) => (
                <div class="border-bottom mb-2">
                  <Item weight={item.weight} url={item.url} setTotal={setTotal} total={total} />
                </div>
              ))}
            </div>

          </div>
        </div>
        {total < 50 &&
          <div class="ms-5">
            <h2>Weight: {total} lbs</h2>
          </div>}
          {total > 50 &&
          <div class="ms-5">
            <h2 class="text-danger">Weight: {total} lbs - OVERWEIGHT</h2>
          </div>}
      </main>
    </div>
  )
}

export default Home;
